/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:769f27dc-4c59-4378-ba4b-2a9405b28466",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_dcu3vFJyH",
    "aws_user_pools_web_client_id": "3kb8f3s124ur5tdc4bo6l2dlk6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mydropboxapp06199b06fd264e4580e20b9173e5effae68c4-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
